apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    helm:
      parameters:
      - name: "argocd.giropopsSenhas.enabled"
        value: "false"
      - name: "argocd.randomLogger.enabled"
        value: "false"
    repoURL: https://github.com/edsonoliveirarodz/descomplicando-gitops.git
    targetRevision: feat/day2
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true 
    - PruneLast=true